### ISSUE TITLE
predict.mgm could return wrong category

### ISSUE THREAD

**Issue by bottleling** [jmbh/mgm#1]
If your testing data contained values that your training data didn't have, but they contained the same number of unique values, `predict.mgm` could return the wrong category.

### Problem 1

```
> unique(dtest[,v])
"2" "3" "4"
> unique(dtrain[,v])
"1" "2" "3" 
````

In this case, Your `Probabilities` variable would contain 3 columns, one for each unqiue value in training data. 

Since `pred_class_id` returns the index of the column with the max value, if the value in first column was the most probable one, then `pred_class_id` returns `1`.

I expect that the `PredictedCat` should be "1" (from the the training data ), 
but it is now "2" (from the testing data) because of the current implementation `PredictedCat <- sort(unique(data[,v]))[pred_class_id] `.

This should probably be changed to `PredictedCat <- names(coefs)[pred_class_id]` to get the correct predicted category. 

### Problem 2

``` 
 X <- model.matrix(form, data= data_m)[,-1]  
... 
for(k in 1:K) {
            # Compute exp(potentials)
            Potentials[,k] <- exp(coefs[[k]][1] + X %*% matrix(coefs[[k]][-1][1:ncol(X)], nrow=length(coefs[[k]][-1][1:ncol(X)])))
          }
```

In this case, when calculating for variable 3, `coefs[[k]][-1][1:ncol(X)]` expects that the first `ncol(X)` elements of the coefficients match the columns of X.
```
> colnames(X)
[1] "V1P2" "V2P2" "V4P2" "V4P3" "V5P2"
```
Expects the coefficients to be like this:
```
(Intercept) -1.629172e+00
V12         .           
V22         .           
V42         .           
V43         6.607575e+00
V52         .           
...
```

But because variable 4 only has `"2" "3" "4"` as values, , coefs looks like

```
(Intercept) -1.629172e+00
V12         .           
V22         .           
V43         .           
V44         6.607575e+00
V52         .           
...      
```

This is my proposed solution
```
for(k in 1:K) {
            # Compute exp(potentials)
            co <-coefs[[k]]
            b<-matrix(0, nrow=ncol(X), ncol=1, dimnames=list(colnames(X),NULL))
            ind_b<-na.omit(match( rownames(co), colnames(X)))
            ind_co<-na.omit(match( colnames(X), rownames(co)))
            b[ind_b]<-co[ind_co]
            Potentials[,k] <- exp(co[1] + X %*% b)
          }
```
However, to prevent duplicates in rownames of the coef, you'll have to name the columns something else like `colnames(data)[1:nNode] <- paste("V",1:nNode,"P", sep="")`, else there would be an issue -- eg variable 11, value 2 would be named named V11**2**, same as variable 1, value 12, also named V1**12**.

**Comment by jmbh** [comment]
Hi bottleling, 

Thank you for reporting this bug and for proposing a solution!

This bug will be fixed in the next mgm version I will release in about a week. Also, there will be a new variable-naming that avoids the issue you mention.

Thanks again,
Jonas

**Comment by jmbh** [comment]
Just uploaded the new version, which should fix both issues.

**Comment by jmbh** [comment]
Just uploaded the latest mgm verison, where both issues should be fixed.

**Comment by leeyang** [comment]
Hi,jmbh
some of my data cannot pass the 'glmnetRequirements' test, including the second and the third condition in  glmnetRequirements because of the poor data quality. But I have to get a result, any suggestions?

**Comment by jmbh** [comment]
leeyang, could you open a new issue for this?
