### ISSUE TITLE
About edge color questions

### ISSUE THREAD

**Issue by dengxuebin** [jmbh/mgm#10]
I had some questions:
1. why have the signs "1/-1" sometimes, and on the other time, no 1/-1, which cause the edge color always darkgrey. I looked at the $pairwise$wadj, the value is very small. Is it the answer? Maybe you have more reasonable explanation. 

2.  Whether "1"(green) represent positive correlation and "-1"(red) represent negative correlation between two nodes?

Please help me if it is convenient for you. Thanks a lot!

**Comment by jmbh** [comment]
-1 and 1 indicate a negative and positive linear relationship; if there is a 0 then the sign is undefined (for categorical variables), if there is an NA, then the corresponding relationship is estimated to be zero

Hope this helps!

Jonas

**Comment by dengxuebin** [comment]
Thanks for your reply. I still had some questions.

1. my data included 60 likert variable(4 levels) and 4 binary variable which I only assigned "c" to  because the ordinal data and binary data are categorical essentially , is it right?

2. I think the edge weight should be not equal to correlation coefficent, may be the function of correlation coefficent because I calculated the correlation matrix with Cramer V and found it different with edge weight in weight adjacency matrix. Am I right ? What is the relationship between edge weights and correlation coefficent really?

3. According to cramer v, it is impossible calculte out a negative value , thus there was no "-1" in signs, is it the reason why I have no "-1" in signs?

I expect your reply. Thanks again!

**Comment by jmbh** [comment]
Hi, 

Sorry for the late reply!

(1) It's not trivial to decide how to model ordinal data. In the end it depends on what you think is the data generating mechanism. If you think the data are generated from a multivariate Gaussian and if the thresholds mapping from the continuous variables to the ordinal variables are not extremely far from unequal, probably modeling them as continuous is not a big mistake. On the other hand, if you model the variables as categorical, you essentially make no assumptions at all about the nature of the pairwise relationships between variables. The downside is, however, that you have to estimate a lot more parameters.

(2) Cramer's V is a pairwise measure, while all the parameters in the mgm models are conditional on adding all other variables in the model

(3) With binarySign=FALSE (default), you will get a 0 for "not defined" in the sign matrix for all interactions involving variables that are specified as categorical.

Jonas
