### ISSUE TITLE
Why were there different wadj matrixs when reorder columns using mgm?

### ISSUE THREAD

**Issue by dengxuebin** [jmbh/mgm#11]
I found the results of wadj were different when I used mgm estimate different orders of column of dataframe  like following: 
sdr<-sdr[,c(1:14),c(34:64),c(15:33)] .  
All the variables are treated as categorical. It includes 60 4-levels and 4 binarys. The code was like:
types<-rep("c",64)
level <-c(rep(4,10),2,rep(4,23),2,2,rep(4,23),2,rep(4,4))
Networkm_sdr<- mgm(data = as.matrix(sdr), 
        type = types,
        level = level,
        k = 2, threshold = "HW",
        lambdaSel="EBIC",
        lambdaGam = 0.5, 
        pbar = T)  

Observation is 2864.
I found the difference by the nnzero command, the results were:
nnzero(Networkm_sdr$pairwise$wadj)
[1] 1042
nnzero(Networkm$pairwise$wadj)
[1] 1046

Theoretically I think the results are the same because the whole data is unchanged and just reordered. Could you give me some suggestions? Hope your replay.thanks !

**Comment by jmbh** [comment]
Hi,

Sorry for the late reply. 

Yes, the number of nonzero elements should not change when you change the order of the columns. Can you give me a reproducible example of this?

Thanks,
Jonas
