### ISSUE TITLE
cannot load mgm package

### ISSUE THREAD

**Issue by tfblanken** [jmbh/mgm#12]
(Using R version 3.6.2)

When loading the mgm package I get an error that there's no package called 'ggm'. 
`Loading required package: mgm
Registered S3 methods overwritten by 'huge':
  method    from   
  plot.sim  BDgraph
  print.sim BDgraph
Error: package or namespace load failed for ‘mgm’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘ggm’`

And trying to install the package 'ggm' gives another error message:
`ERROR: dependency ‘graph’ is not available for package ‘ggm’
removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ggm’
Warning in install.packages :
  installation of package ‘ggm’ had non-zero exit status`

Cannot seem to get out of this loop (because 'graph' is not a package?) to get mgm working, any tips?

**Comment by jmbh** [comment]
Is this still an issue?
