### ISSUE TITLE
Problem uploading package

### ISSUE THREAD

**Issue by icasas** [jmbh/mgm#15]
I installed "mgm" and then I got this error message when I tried to upload it into memory:
> library("mgm")
Error: package or namespace load failed for ‘mgm’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘mnormt’

**Comment by jmbh** [comment]
Hi Icasas, 

Did you try installing the package "mnormt" manually and then load mgm?

Jonas

**Comment by icasas** [comment]
Hi Jonas,

I tried to install the mgm and it all worked fine, but they I got the error when I used “library(mgm)”. I haven’t installed the “mnormt” manually and it is not available for R version 3.6.2.

Best,
Isabel

**Comment by jmbh** [comment]
Hi Isabel, 

You shouldn't need the mnormt package for mgm, but maybe it depends on it indirectly.

The mnormt package requires R 4.0.0, which is probably the reason why you cannot install it:
https://cran.r-project.org/web/packages/mnormt/index.html

I guess updating to R 4.0.0 / 4.0.1 should solve your problem

Jonas

**Comment by icasas** [comment]
Hi Jonas,

I did all that. Intalled the R 4.0.1 library and now I get:
Error: package or namespace load failed for ‘mgm’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
there is no package called ‘glmnet’

I hope this helps.
Best,
Isabel
