### ISSUE TITLE
mvar: coef(fit, s = lambda)[[catIter]] : subscript out of bounds

### ISSUE THREAD

**Issue by piccirillom** [jmbh/mgm#19]
Hi Jonas,

I'm trying to run a mvar using the following code: 
TestMVAR <- mvar(Networks_imp_sel2, type = c("c", "c", "c", "p", "p", "c", "c", "p", "p", "g", "p", "p", "g", "g", "g"), 
                 level = c(21, 4, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1),
                 lamdaSel = "EBIC", alphaSel = "EBIC", scale = TRUE,
                 beepvar = Networks_imp_sel2$timeday,
                 dayvar = Networks_imp_sel2$studyday,
                 lags = 1)

runs for about 5-10% then produces this error: "coef(fit, s = lambda)[[catIter]] : subscript out of bounds"

I'm using EMA data from 51 ppl collected 4x/day for 21 days and imputed missingness. I removed the ID variable in this code (though was receiving the same error with the ID variable in). All variables are specified as numeric/integer. I reviewed the code for mvar but can't find where the error might be occurring or how to resolve it. I'm able to run an mgm model with this dataset ok (in case that's helpful to know)

Thanks very much!
Marilyn

**Comment by jmbh** [comment]
Hi Marilyn, 

Thanks for reporting this!

Could you send me a reproducible example of this error?

Thanks,
Jonas

**Comment by piccirillom** [comment]
Sure! Here is test data and code. Same error but with some additional warnings thrown in.
3 ppl, 21 days, 4x/day
categorical "ID", "Day", "Time" variables
binary "Eat" variable
poisson "PosAff" variable
gaussian "NegAff" variable
[TestCode and Data.zip](https://github.com/jmbh/mgm/files/5881123/TestCode.and.Data.zip)
