### ISSUE TITLE
MGM erro message 

### ISSUE THREAD

**Issue by LemeDEC** [jmbh/mgm#21]
When I try to estimate my mgm model, a message is returned to me:

 100%Error in sign(l_w_par[[2]][2]) : 
  non-numeric argument to mathematical function

Please, How Can I fix it? 

I have the version RStudio 2021.09.0 Build 351

Thank you

**Comment by jmbh** [comment]
Hi LemeDEC, 

Thanks for reporting this.

Could you give me a reproducible example for the error?

Thanks,
Jonas

**Comment by ClarissaFreitas** [comment]
Hi Jonas
I am getting the same error.
Could you help me?

library(mgm)

# -------------------- Estimating Mixed Graphical Models --------------------

set.seed(1)
fit_mgm <- mgm(data = Redes,
               type = c("g",  # "Idade" -> 1
                        "g",  # "Autoestima"  -> 2
                        "g",  # "AutoEficacia"  -> 3
                        "g",  # "NAOAceitaCAon"  -> 4       
                        "g",  # "Objet"  -> 5               
                        "g",  # "Impul"  -> 6              
                        "g",  # "Estr"  -> 7                
                        "g",  # "Clar"  -> 8
                        "c",  # "Raca" -> 9
                        "c",  # "Escolaridade" -> 10
                        "c",  # "Renda_mensal" -> 11
                        "c",  # "Trat_psico" -> 12
                        "c",  # "Status_Civil" -> 13  
                        "c",  # "Filhos" -> 14   
                        "c",  # "Atividade_remunerad" -> 15
                        "c",  # "Auxilio_gov" -> 16         
                        "c",  # "VPsicolOgica" -> 17  
                        "c",  # "VFisica" -> 18        
                        "c"),  # "VSexual" -> 19       
                        levels = c(1, 1, 1, 1, 1, 1, 1, 1, 
                                   2, 3, 5, 2, 3, 2, 2, 2, 2, 2), 
               k = 2, # K são o número de interações (k = 2, which corresponds to a pairwise MGM (containing at most 2-way interactions)) 
               lambdaSel = "CV",
               lambdaFolds = 100, 
               binarySign = T, # Indica se a relação é positiva ou negativa nas variáveis binárias
               ruleReg = "AND", 
               overparameterize = T)

int <- showInteraction(fit_mgm, int=c(1,19)) 

I verified all data using your code, and it was ok.
 # Checks on data
  if(nrow(Redes) < 2) ('The data matrix has to have at least 2 rows.')
  if(any(!(apply(Redes, 2, class) %in% c('numeric', 'integer')))) stop('Only integer and numeric values permitted.')
  if(missing(Redes)) stop('No data provided.')
  if(any(!is.finite(as.matrix(Redes)))) stop('No infinite values permitted.')
  if(any(is.na(Redes))) stop('No missing values permitted.')
  
  The error that appears is:
  
  Error in sign(l_w_par[[2]][2]) :
non-numeric argument to mathematical function

Please, how can I fix it?

Thanks,
Clarissa

**Comment by jmbh** [comment]
Can you transform your data into "matrix" format (e.g., not "data.frame" or similar) and try again? 

If that doesn't solve it, please send me a reproducible example (i.e., including the data), so I can reproduce this.

Thanks,
Jonas
