### ISSUE TITLE
function calcLL

### ISSUE THREAD

**Issue by markov10000** [jmbh/mgm#22]
in calcLL function

LL_model <- dnorm(y, mean = predicted_mean, sd = 1, log = TRUE)

Why sd is set to 1?

**Comment by jmbh** [comment]
Hi Markov10000, 

This is because each variable is scaled to mean=0, sd=1.

Best wishes,
Jonas

**Comment by markov10000** [comment]
> Hi Markov10000,
> 
> This is because each variable is scaled to mean=0, sd=1.
> 
> Best wishes, Jonas

Hi Jonas,

Thank you for your reply.

In the likelihood function, sigma is the standard deviation of the errors which is unknown. That is why I cannot understand sd=1.

Besides, I did not find the line (e.g., in mvar.R or tvmvar.R) where variables are scaled. Could you give me a hint?

Kind regards

**Comment by jmbh** [comment]
Hi Markov10000,

Indeed, the SD should be the SD of the residual. This is fixed now. Thanks for spotting this!

Regarding your other question: tvmvar.R calls mvar.R, which scales the data on lines 144-149. 

Best wishes,
Jonas
