### ISSUE TITLE
application condition

### ISSUE THREAD

**Issue by mengyuanYUAN123** [jmbh/mgm#23]
I'm contrusting network using cross-sectional data with 'mgm' package. Here are my issues: I want to kown if mgm package can include non-nomal continuous variables, and how to compare different groups in NetworkComparisonTest package (to my knowledge, it has only been used to deal with Gaussian/binary data)?

**Comment by jmbh** [comment]
Hi mengyuanYUAN123, 

Currently, you cannot include non-Gaussian continuous variables. I'm not sure whether the NCT package supports mgm. However, the permutation test in NCT is relatively straightforward to code up yourself.

Best wishes,
Jonas
