### ISSUE TITLE
Error. No infinite values permitted.

### ISSUE THREAD

**Issue by paniblanca** [jmbh/mgm#25]
When using the package, the following error shows up: 
Error in mgm(data = predict_like_it0$data, type = c(rep("c", 8)), level = c(5,  : 
No infinite values permitted.

This the code i'm using: 
predict_like_it0 <- mgm(data = predict_like_it0$data, 
   type = c(rep("c", 8)), 
   level = c(rep (5, 8)),
   labels = c("Ep", "Fl", "Dr", "Wf", "Eq", "TA", "EC", "CC"),
   lambdaSel = "EBIC", 
   lambdaGam = 0.5)

The matrix for the data looks fine and the rest consists of 8 variables from likert-scale ranging from 1 to 5 (categorical).

**Comment by jmbh** [comment]
Can you try providing the data as a "matrix" object instead?

**Comment by paniblanca** [comment]
Yes, I have tried to add this instead but it shows up the same. 

data = as.matrix(subset(data_like, select = c(like_ep, like_fl, like_dr, 
                                                         like_wf, like_eq, like_ta, 
                                                         like_ec, like_cc)))

**Comment by jmbh** [comment]
OK, then I'd need to have a look at a reproducible example!

**Comment by paniblanca** [comment]
Solved it! Thank you!

**Comment by RosaSinclair** [comment]
Paniblanca - how did you solve it? I'm getting the same message and I'm unsure why.
