### ISSUE TITLE
How to adjust the numbers of decimal when compute the predictability

### ISSUE THREAD

**Issue by GangYLu** [jmbh/mgm#27]
Hi, jmbh

When I want to use the function "predict" to compute the predictability, the R² value of each node only has three decimals. Is it possible to expand the numbers of decimal so that each R² value can show four decimals?

![picture](https://github.com/jmbh/mgm/assets/119727095/3e2fc1d9-9669-4d90-b31e-b025936bae33)

**Comment by jmbh** [comment]
Hi GangYLu,

I added an argument to predict() in the dev version which allows you control the number of decimals:

# Install dev version from Github
library(devtools)
install_github("jmbh/mgm")
library(mgm)

# Fit mgm to example dataset
fit_k3 <- mgm(data = autism_data$data,
              type = autism_data$type,
              level = autism_data$lev,
              k = 3)

# Get prediction errors/predictability values with 5 decimals
pred_obj <- predict(fit_k3, autism_data$data, errordecimals = 5)
pred_obj$errors 


Best,
Jonas

**Comment by GangYLu** [comment]
Dear Dr.Jonas

I'm sorry for replying so late. I have missed this message. Thanks for your kindly help. 

Best,
Gangyuan
