### ISSUE TITLE
colMeans error thrown when using a categorical variable

### ISSUE THREAD

**Issue by ianhussey** [jmbh/mgm#4]
I'm trying to apply mgm to data that has 1 categorical variable with 95 levels and 9 continuous variables. If I exclude the categorical it throws no errors, but if I include it I get the error 
"Error in colMeans(x, na.rm = TRUE) : 'x' must be numeric". I tried to find a call to colMeans() in the source code but couldn't track down the error. The data type is definitely correct for all variables, and there is no missing data. Do you have any suggestions as to what's causing this?

```
types <- c(rep("c", 1), rep("g", ncol(data)-1))
levels <- c(nlevels(data$domain), rep(1, ncol(data)-1))

network <- 
    mgm(data = data, 
        type = types,
        level = levels,
        scale = TRUE,
        ruleReg = "OR",
        lambdaSel = "EBIC",
        lambdaGam = 0.5,
        k = 2,
        overparameterize = FALSE)
```

**Comment by jmbh** [comment]
Hi Ian, thanks for reporting this. Any chance you could share (an anonymized version of) your data so I can reproduce this error? Thanks!

**Comment by ianhussey** [comment]
Sure thing! Here's a link to a minimally reproducable example: https://www.dropbox.com/sh/01xqofefdq7ubdn/AAAXv3YSKtne7LIgvKzZJO5Ia?dl=0

**Comment by ianhussey** [comment]
I think I found a workaround. My data supplies the categorical variable as a factor with string names. If I recode this variable as an integer, mgm runs correctly. The issue seems to be related to mgm trying to scale the categorical variable and/or converting this variable from integer to categorical internally.

**Comment by jmbh** [comment]
The variables you enter are of class character, while mgm() requires all data to be numeric/integer (see ?mgm). I adapted the input checks though, such that you get now a (more) informative error message.
