### ISSUE TITLE
predict and data.frame

### ISSUE THREAD

**Issue by jerryspan** [jmbh/mgm#5]
I am trying to run the simple example from paper "How well do network models predict observations? On the importance of predictability in network models"

```
library(httr)
library(qgraph)
library(mgm)

url="https://tinyurl.com/yau3xms2"
GET(url, write_disk("Wicherts2016_Mood.RDS"))
dlist_ts <- readRDS("Wicherts2016_Mood.RDS")

dim(dlist_ts$data_mood) #1478,9
length(dlist_ts$data_time$beepno)  #1478

set.seed(3)
var_obj <- mvar(data = dlist_ts$data_mood,
                type = rep("g", 9),
                lev = rep(1, 9),
                lags = 1,
                consec=dlist_ts$data_time$beepno)

p_obj2 <- predict(var_obj, data=dlist_ts$data_mood,errorCon = c("R2"))
```

But I am getting the:

> Error in model.frame.default(object, data, xlev = xlev) : 
>   'data' must be a data.frame, not a matrix or an array

As far as I can tell, it is a data frame.

> class(dlist_ts$data_mood)
[1] "data.frame"

What am I missing?

**Comment by jmbh** [comment]
Thanks for reporting this. I fixed the bug in the Github version!
