### ISSUE TITLE
Scale argument default value...?

### ISSUE THREAD

**Issue by heinonmatti** [jmbh/mgm#7]
This may be a silly question, but what's the default value for scale? Not seeing it mentioned in the documentation...

> If scale = TRUE, all Gaussian nodes (specified by "g" in type) are centered and divided by their standard deviation. Scaling is recommended, because otherwise the penalization of a parameter depends on the variance of the associated predictor.

**Comment by jmbh** [comment]
The default value is scale = TRUE, and this is indeed not indicated in the mgm documentation. Thanks for pointing this out, I will add this to the documentation in the next version.
