### ISSUE TITLE
bwSelect "argument is of length zero"

### ISSUE THREAD

**Issue by heinonmatti** [jmbh/mgm#8]
Hi,

I'm getting this in mgm 1.2.7 with code that has worked previously if I'm not mistaken:

> Error in if (args$d > (p - 1)) { : argument is of length zero

Reproducible example:

``` 
test <- data.frame(a = base::sample(1:49, size = 228, replace = TRUE),
                   b = base::sample(1:49, size = 228, replace = TRUE),
                   c = base::sample(1:49, size = 228, replace = TRUE),
                   d = base::sample(1:49, size = 228, replace = TRUE),
                   e = base::sample(1:49, size = 228, replace = TRUE))

bwSeq <- seq(0.01, 1, length = 10) # ten equally spaced values in [0:01; 1]

dftime <- seq(as.Date("2000/1/1"), by = "day", length.out = 228)
time_test <- dftime - dftime[1]
time_test <- as.numeric(time_test)
time_test <- time_test / max(time_test) # normalise time, not necessary for mgm, though

bw_mgm_object <- mgm::bwSelect(data = test,
  type = rep("g", 5),
  level = rep(1, 5),
  bwSeq = bwSeq,
  bwFolds = 2,
  bwFoldsize = 20,
  modeltype = "mgm",
  lags = 1,
  scale = TRUE,
  timepoints = time_test)
```

devtools::session_info() printout:

- Session info -----------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.3 (2019-03-11)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Finnish_Finland.1252        
 ctype    Finnish_Finland.1252        
 tz       Europe/Helsinki             
 date     2019-06-18                  

- Packages ---------------------------------------------------------------------------------------
 package               * version    date       lib source                                   
 abind                   1.4-5      2016-07-21 [1] CRAN (R 3.5.0)                           
 acepack                 1.4.1      2016-10-29 [1] CRAN (R 3.5.0)                           
 assertthat              0.2.1      2019-03-21 [1] CRAN (R 3.5.3)                           
 backports               1.1.4      2019-04-10 [1] CRAN (R 3.5.3)                           
 base64enc               0.1-3      2015-07-28 [1] CRAN (R 3.5.0)                           
 BDgraph                 2.59       2019-05-06 [1] CRAN (R 3.5.3)                           
 boot                    1.3-22     2019-04-26 [2] CRAN (R 3.5.3)                           
 bootnet                 1.2.2      2019-05-09 [1] CRAN (R 3.5.3)                           
 broom                   0.5.2      2019-04-07 [1] CRAN (R 3.5.3)                           
 callr                   3.2.0      2019-03-15 [1] CRAN (R 3.5.3)                           
 candisc                 0.8-0      2017-09-19 [1] CRAN (R 3.5.1)                           
 car                     3.0-2      2018-08-23 [1] CRAN (R 3.5.1)                           
 carData                 3.0-2      2018-09-30 [1] CRAN (R 3.5.1)                           
 casnet                  0.1.4      2019-06-15 [1] Github (Fredhasselman/casnet@d360278)    
 cellranger              1.1.0      2016-07-27 [1] CRAN (R 3.5.0)                           
 checkmate               1.9.3      2019-05-03 [1] CRAN (R 3.5.3)                           
 cli                     1.1.0      2019-03-19 [1] CRAN (R 3.5.3)                           
 cluster                 2.0.9      2019-05-01 [1] CRAN (R 3.5.3)                           
 cmprsk                  2.2-7      2014-06-17 [1] CRAN (R 3.5.0)                           
 codetools               0.2-16     2018-12-24 [2] CRAN (R 3.5.3)                           
 colorspace              1.4-1      2019-03-18 [1] CRAN (R 3.5.3)                           
 corpcor                 1.6.9      2017-04-01 [1] CRAN (R 3.5.0)                           
 crayon                  1.3.4      2017-09-16 [1] CRAN (R 3.5.0)                           
 curl                    3.3        2019-01-10 [1] CRAN (R 3.5.2)                           
 d3Network               0.5.2.1    2015-01-31 [1] CRAN (R 3.5.0)                           
 data.table              1.12.2     2019-04-07 [1] CRAN (R 3.5.3)                           
 DBI                     1.0.0      2018-05-02 [1] CRAN (R 3.5.0)                           
 desc                    1.2.0      2018-05-01 [1] CRAN (R 3.5.1)                           
 devtools                2.0.2      2019-04-08 [1] CRAN (R 3.5.3)                           
 digest                  0.6.19     2019-05-20 [1] CRAN (R 3.5.3)                           
 dplyr                 * 0.8.1      2019-05-14 [1] CRAN (R 3.5.3)                           
 eigenmodel              1.10       2018-06-03 [1] CRAN (R 3.5.0)                           
 ellipse                 0.4.1      2018-01-05 [1] CRAN (R 3.5.0)                           
 Epi                     2.37       2019-05-23 [1] CRAN (R 3.5.3)                           
 EstimateGroupNetwork    0.1.2      2017-03-20 [1] CRAN (R 3.5.1)                           
 etm                     1.0.4      2018-07-11 [1] CRAN (R 3.5.1)                           
 evaluate                0.14       2019-05-28 [1] CRAN (R 3.5.3)                           
 fdrtool                 1.2.15     2015-07-08 [1] CRAN (R 3.5.0)                           
 forcats               * 0.4.0      2019-02-17 [1] CRAN (R 3.5.2)                           
 foreach                 1.4.4      2017-12-12 [1] CRAN (R 3.5.0)                           
 foreign                 0.8-71     2018-07-20 [1] CRAN (R 3.5.1)                           
 Formula                 1.2-3      2018-05-03 [1] CRAN (R 3.5.0)                           
 fs                      1.3.1      2019-05-06 [1] CRAN (R 3.5.3)                           
 gdata                   2.18.0     2017-06-06 [1] CRAN (R 3.5.0)                           
 GeneNet                 1.2.13     2015-08-02 [1] CRAN (R 3.5.0)                           
 generics                0.0.2      2018-11-29 [1] CRAN (R 3.5.1)                           
 ggm                     2.3        2015-01-21 [1] CRAN (R 3.5.0)                           
 ggplot2               * 3.1.1      2019-04-07 [1] CRAN (R 3.5.3)                           
 glasso                  1.10       2018-07-13 [1] CRAN (R 3.5.1)                           
 glmnet                  2.0-18     2019-05-20 [1] CRAN (R 3.5.3)                           
 glue                    1.3.1      2019-03-12 [1] CRAN (R 3.5.3)                           
 gridBase                0.4-7      2014-02-24 [1] CRAN (R 3.5.3)                           
 gridExtra               2.3        2017-09-09 [1] CRAN (R 3.5.0)                           
 gtable                  0.3.0      2019-03-25 [1] CRAN (R 3.5.1)                           
 gtools                  3.8.1      2018-06-26 [1] CRAN (R 3.5.0)                           
 haven                   2.1.0      2019-02-19 [1] CRAN (R 3.5.2)                           
 heplots                 1.3-5      2018-04-03 [1] CRAN (R 3.5.1)                           
 Hmisc                   4.2-0      2019-01-26 [1] CRAN (R 3.5.2)                           
 hms                     0.4.2      2018-03-10 [1] CRAN (R 3.5.0)                           
 htmlTable               1.13.1     2019-01-07 [1] CRAN (R 3.5.2)                           
 htmltools               0.3.6      2017-04-28 [1] CRAN (R 3.5.0)                           
 htmlwidgets             1.3        2018-09-30 [1] CRAN (R 3.5.1)                           
 httr                    1.4.0      2018-12-11 [1] CRAN (R 3.5.1)                           
 huge                    1.3.2      2019-04-08 [1] CRAN (R 3.5.3)                           
 igraph                  1.2.4.1    2019-04-22 [1] CRAN (R 3.5.3)                           
 invctr                  0.1.0      2019-03-07 [1] CRAN (R 3.5.3)                           
 IsingFit                0.3.1      2016-09-07 [1] CRAN (R 3.5.1)                           
 IsingSampler            0.2        2015-03-02 [1] CRAN (R 3.5.0)                           
 iterators               1.0.10     2018-07-13 [1] CRAN (R 3.5.1)                           
 jomo                    2.6-8      2019-05-21 [1] CRAN (R 3.5.3)                           
 jpeg                    0.1-8      2014-01-23 [1] CRAN (R 3.5.0)                           
 jsonlite                1.6        2018-12-07 [1] CRAN (R 3.5.1)                           
 knitr                 * 1.23       2019-05-18 [1] CRAN (R 3.5.3)                           
 lattice                 0.20-38    2018-11-04 [2] CRAN (R 3.5.3)                           
 latticeExtra            0.6-28     2016-02-09 [1] CRAN (R 3.5.0)                           
 lavaan                  0.6-3      2018-09-22 [1] CRAN (R 3.5.2)                           
 lazyeval                0.2.2      2019-03-15 [1] CRAN (R 3.5.3)                           
 lme4                    1.1-21     2019-03-05 [1] CRAN (R 3.5.3)                           
 longitudinal            1.1.12     2015-07-08 [1] CRAN (R 3.5.0)                           
 lubridate               1.7.4      2018-04-11 [1] CRAN (R 3.5.0)                           
 magrittr                1.5        2014-11-22 [1] CRAN (R 3.5.0)                           
 MASS                    7.3-51.4   2019-04-26 [1] CRAN (R 3.5.3)                           
 Matrix                  1.2-17     2019-03-22 [1] CRAN (R 3.5.3)                           
 matrixcalc              1.0-3      2012-09-15 [1] CRAN (R 3.5.0)                           
 memoise                 1.1.0      2017-04-21 [1] CRAN (R 3.5.0)                           
 mgcv                    1.8-28     2019-03-21 [1] CRAN (R 3.5.3)                           
 mgm                     1.2-7      2019-05-09 [1] Github (jmbh/mgm@029ab66)                
 mice                    3.5.0      2019-05-13 [1] CRAN (R 3.5.3)                           
 minqa                   1.2.4      2014-10-09 [1] CRAN (R 3.5.0)                           
 mitml                   0.3-7      2019-01-07 [1] CRAN (R 3.5.2)                           
 mitools                 2.4        2019-04-26 [1] CRAN (R 3.5.3)                           
 mnormt                  1.5-5      2016-10-15 [1] CRAN (R 3.5.0)                           
 modelr                  0.1.4      2019-02-18 [1] CRAN (R 3.5.1)                           
 munsell                 0.5.0      2018-06-12 [1] CRAN (R 3.5.0)                           
 mvtnorm                 1.0-10     2019-03-05 [1] CRAN (R 3.5.2)                           
 NetworkComparisonTest   2.0.1      2016-10-29 [1] CRAN (R 3.5.0)                           
 NetworkToolbox          1.2.3      2019-01-31 [1] CRAN (R 3.5.2)                           
 networktools            1.2.1      2019-05-20 [1] CRAN (R 3.5.3)                           
 networktree             0.2.2      2019-05-27 [1] Github (paytonjjones/networktree@81ec27d)
 nlme                    3.1-140    2019-05-12 [1] CRAN (R 3.5.3)                           
 nloptr                  1.2.1      2018-10-03 [1] CRAN (R 3.5.1)                           
 nnet                    7.3-12     2016-02-02 [2] CRAN (R 3.5.3)                           
 nnls                    1.4        2012-03-19 [1] CRAN (R 3.5.0)                           
 numDeriv                2016.8-1.1 2019-06-06 [1] CRAN (R 3.5.3)                           
 openxlsx                4.1.0.1    2019-05-28 [1] CRAN (R 3.5.3)                           
 pacman                  0.5.1      2019-03-11 [1] CRAN (R 3.5.3)                           
 pan                     1.6        2018-06-29 [1] CRAN (R 3.5.0)                           
 parcor                  0.2-6      2014-09-04 [1] CRAN (R 3.5.0)                           
 patchwork             * 0.0.1      2018-11-21 [1] Github (thomasp85/patchwork@fd7958b)     
 pbapply                 1.4-0      2019-02-05 [1] CRAN (R 3.5.2)                           
 pbivnorm                0.6.0      2015-01-23 [1] CRAN (R 3.5.0)                           
 pillar                  1.4.1      2019-05-28 [1] CRAN (R 3.5.3)                           
 pkgbuild                1.0.3      2019-03-20 [1] CRAN (R 3.5.3)                           
 pkgconfig               2.0.2      2018-08-16 [1] CRAN (R 3.5.1)                           
 pkgload                 1.0.2      2018-10-29 [1] CRAN (R 3.5.1)                           
 plotrix                 3.7-5      2019-04-07 [1] CRAN (R 3.5.3)                           
 plyr                    1.8.4      2016-06-08 [1] CRAN (R 3.5.0)                           
 png                     0.1-7      2013-12-03 [1] CRAN (R 3.5.0)                           
 polynom                 1.4-0      2019-03-22 [1] CRAN (R 3.5.3)                           
 ppls                    1.6-1.1    2018-07-20 [1] CRAN (R 3.5.1)                           
 prettyunits             1.0.2      2015-07-13 [1] CRAN (R 3.5.0)                           
 processx                3.3.1      2019-05-08 [1] CRAN (R 3.5.3)                           
 ps                      1.3.0      2018-12-21 [1] CRAN (R 3.5.2)                           
 psych                   1.8.12     2019-01-12 [1] CRAN (R 3.5.2)                           
 purrr                 * 0.3.2      2019-03-15 [1] CRAN (R 3.5.3)                           
 qgraph                  1.6.2      2019-05-09 [1] CRAN (R 3.5.3)                           
 R.methodsS3             1.7.1      2016-02-16 [1] CRAN (R 3.5.0)                           
 R.oo                    1.22.0     2018-04-22 [1] CRAN (R 3.5.0)                           
 R.utils                 2.8.0      2019-02-14 [1] CRAN (R 3.5.2)                           
 R6                      2.4.0      2019-02-14 [1] CRAN (R 3.5.2)                           
 RColorBrewer            1.1-2      2014-12-07 [1] CRAN (R 3.5.0)                           
 Rcpp                    1.0.1      2019-03-17 [1] CRAN (R 3.5.3)                           
 readr                 * 1.3.1      2018-12-21 [1] CRAN (R 3.5.2)                           
 readxl                  1.3.1      2019-03-13 [1] CRAN (R 3.5.3)                           
 relaimpo                2.2-3      2018-03-10 [1] CRAN (R 3.5.0)                           
 remotes                 2.0.4      2019-04-10 [1] CRAN (R 3.5.3)                           
 reshape2                1.4.3      2017-12-11 [1] CRAN (R 3.5.0)                           
 rio                     0.5.16     2018-11-26 [1] CRAN (R 3.5.1)                           
 rjson                   0.2.20     2018-06-08 [1] CRAN (R 3.5.0)                           
 rlang                   0.3.4      2019-04-07 [1] CRAN (R 3.5.3)                           
 rmarkdown               1.13       2019-05-22 [1] CRAN (R 3.5.3)                           
 rpart                   4.1-15     2019-04-12 [1] CRAN (R 3.5.3)                           
 rprojroot               1.3-2      2018-01-03 [1] CRAN (R 3.5.0)                           
 rstudioapi              0.10       2019-03-19 [1] CRAN (R 3.5.3)                           
 rvest                   0.3.4      2019-05-15 [1] CRAN (R 3.5.3)                           
 scales                  1.0.0      2018-08-09 [1] CRAN (R 3.5.1)                           
 sessioninfo             1.1.1      2018-11-05 [1] CRAN (R 3.5.1)                           
 smacof                  1.10-8     2018-06-14 [1] CRAN (R 3.5.1)                           
 stringi                 1.4.3      2019-03-12 [1] CRAN (R 3.5.3)                           
 stringr               * 1.4.0      2019-02-10 [1] CRAN (R 3.5.2)                           
 survey                  3.36       2019-04-27 [1] CRAN (R 3.5.3)                           
 survival                2.44-1.1   2019-04-01 [1] CRAN (R 3.5.3)                           
 testthat                2.1.1      2019-04-23 [1] CRAN (R 3.5.3)                           
 tibble                * 2.1.3      2019-06-06 [1] CRAN (R 3.5.3)                           
 tidyr                 * 0.8.3      2019-03-01 [1] CRAN (R 3.5.3)                           
 tidyselect              0.2.5      2018-10-11 [1] CRAN (R 3.5.1)                           
 tidyverse             * 1.2.1      2017-11-14 [1] CRAN (R 3.5.1)                           
 usethis                 1.5.0      2019-04-07 [1] CRAN (R 3.5.3)                           
 viridis                 0.5.1      2018-03-29 [1] CRAN (R 3.5.1)                           
 viridisLite             0.3.0      2018-02-01 [1] CRAN (R 3.5.0)                           
 weights                 1.0        2018-10-16 [1] CRAN (R 3.5.1)                           
 whisker                 0.3-2      2013-04-28 [1] CRAN (R 3.5.0)                           
 withr                   2.1.2      2018-03-15 [1] CRAN (R 3.5.0)                           
 wordcloud               2.6        2018-08-24 [1] CRAN (R 3.5.1)                           
 xfun                    0.7        2019-05-14 [1] CRAN (R 3.5.3)                           
 xml2                    1.2.0      2018-01-24 [1] CRAN (R 3.5.0)                           
 yaml                    2.2.0      2018-07-25 [1] CRAN (R 3.5.1)                           
 zip                     2.0.2      2019-05-13 [1] CRAN (R 3.5.3)                           
 zoo                     1.8-6      2019-05-28 [1] CRAN (R 3.5.3)                           

[1] C:/rlibs/3.4.2
[2] C:/Program Files/R/R-3.5.3/library

**Comment by jmbh** [comment]
Hi, 

Thanks a lot for reporting and for the reproducible example.

This is fixed in the latest devel version on Github (1-2.7).

Thanks,
Jonas
