### ISSUE TITLE
Stability selection

### ISSUE THREAD

**Issue by gokceneraslan** [jmbh/mgm#9]
Thanks for amazing R package. I was wondering if it is possible to add [stability selection](https://rss.onlinelibrary.wiley.com/doi/10.1111/j.1467-9868.2010.00740.x) as an extra fitting method. It uses LARS or glmnet as backend and fits the model 50-100 times on subsets of the data and combines the frequency of selection of a variable with nice PFER-based error control. See https://github.com/hofnerb/stabs/ for more details. I think this idea is already proposed by Sedgewick et al. before (https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-1039-0), but 
the code (https://github.com/benoslab/causalMGM) is not well-implemented and requires Java.

What do you think? Maybe @hofnerb can share his thoughts with us too.

**Comment by jmbh** [comment]
Hi @gokceneraslan, 

Thanks for this suggestion. I have been meaning to implement this for quite a while (we already announced this in the paper a long while ago, see p. 43 in https://arxiv.org/pdf/1510.06871.pdf), but I never got around doing this. 

I'm currently finishing my dissertation, but I'll have a look at how much coding would be involved in implementing this in January.

Thanks  & Cheers,
Jonas
